apiVersion: v1
kind: Secret
metadata:
  name: dockerio
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogIlkyRnliRzl6ZG1Gc1pXNWphV0YwT2tOaGNteHZjeTVVTTIxd01ISTBiQT09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
spec:
  selector:
    matchLabels:
      app: echo-api
  template:
    metadata:
      labels:
        app: echo-api
    spec:
      containers:
      - name: echo-app
        image: cavalen/http-https-echo:25
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: dockerio
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api-svc
spec:
  type: ClusterIP
  selector:
    app: echo-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
