apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-api
spec:
  selector:
    matchLabels:
      app: echo-api
  template:
    metadata:
      labels:
        app: echo-api
    spec:
      containers:
        name: echo-app
        image: mendhak/http-https-echo:24
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echo-api-svc
spec:
  type: ClusterIP
  selector:
    app: echo-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
